name: PicSweep
options:
  bundleIdPrefix: com.picsweep
  deploymentTarget:
    iOS: 17.6.1
  platforms:
    iOS:
      baseSDK: iOS
      supportedPlatforms: [iphoneos, iphonesimulator]
targets:
  PicSweep:
    type: application
    platform: iOS
    sources:
      - path: Sources/PicSweep
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.picsweep.app
        DEVELOPMENT_TEAM: "Jordan DeAndrade (Personal Team)"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        PROVISIONING_PROFILE_SPECIFIER: ""
        TARGETED_DEVICE_FAMILY: 1  # 1 = iPhone, 2 = iPad
        SUPPORTS_MACCATALYST: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        MARKETING_VERSION: 5.1.0
        CURRENT_PROJECT_VERSION: 1
        SUPPORTED_PLATFORMS: iphoneos iphonesimulator
        SDKROOT: iphoneos
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: 5.0
        IPHONEOS_DEPLOYMENT_TARGET: 17.6.1
        VALIDATE_WORKSPACE: YES
        ENABLE_BITCODE: NO
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    info:
      path: Sources/PicSweep/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIRequiredDeviceCapabilities:
          - arm64
          - arm64e
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSPhotoLibraryUsageDescription: "PicSweep needs access to your photo library to help you organize and clean up your photos."
        NSCameraUsageDescription: "PicSweep needs access to your camera to capture photos for organization."
        NSLocationWhenInUseUsageDescription: "PicSweep uses your location to organize photos by place."
        NSLocationAlwaysAndWhenInUseUsageDescription: "PicSweep uses your location to organize photos by place, even when the app is in the background."
        NSFaceIDUsageDescription: "PicSweep uses Face ID to secure your private photos."
        NSMicrophoneUsageDescription: "PicSweep needs access to your microphone for voice commands and audio notes."
        NSUserTrackingUsageDescription: "PicSweep uses tracking data to provide personalized photo organization suggestions."
        ITSAppUsesNonExemptEncryption: false
        UIRequiresFullScreen: true
        UIBackgroundModes:
          - remote-notification
          - fetch
          - processing
        CFBundleShortVersionString: "5.1.0"
        CFBundleVersion: "1"
        LSApplicationQueriesSchemes:
          - photos-redirect
        UIViewControllerBasedStatusBarAppearance: true
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIStatusBarHidden: false 