# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
    
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: "5.5"
    
    - name: Build
      run: |
        xcodebuild -scheme PicSweep -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' clean build
    
    - name: Run tests
      run: |
        xcodebuild -scheme PicSweep -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' test

